<?php

$thoughtsOfTheDay = [
    "Integrity is the foundation of public service.",
    "Honesty and transparency build trust in governance.",
    "A disciplined officer ensures disciplined administration.",
    "Public service is a responsibility, not a privilege.",
    "Efficiency in work reflects respect for public time.",
    "Fair decisions create a strong and just system.",
    "Accountability is the key to good governance.",
    "Serve the public with dedication and sincerity.",
    "A responsible officer leads by example.",
    "Commitment to duty strengthens democracy.",
    "Justice delayed is justice denied.",
    "Every decision should uphold the public interest.",
    "Professional conduct earns public confidence.",
    "Work with integrity, serve with pride.",
    "Public trust is earned through consistent actions.",
    "Discipline and punctuality define effective governance.",
    "Transparency is the cornerstone of good administration.",
    "Serve with empathy, decide with fairness.",
    "Leadership begins with responsibility.",
    "Public office demands ethical excellence.",
    "Dedication to duty ensures national progress.",
    "Impartiality strengthens public faith.",
    "Efficiency and honesty lead to effective service delivery.",
    "Respect for rules ensures respect from society.",
    "A sincere officer is the strength of the system.",
    "Governance succeeds when accountability is upheld.",
    "Service to the nation is service to its people.",
    "Every role matters in nation-building.",
    "Decisions taken with integrity leave lasting impact.",
    "Professionalism reflects institutional strength.",
    "Public service requires patience and perseverance.",
    "Uphold values, deliver results.",
    "A transparent system empowers citizens.",
    "Responsibility today builds trust for tomorrow.",
    "Work silently, let results speak.",
    "Ethical conduct defines true leadership.",
    "Consistency in action builds credibility.",
    "A fair system begins with fair officers.",
    "Service excellence is the goal of governance.",
    "Dedication transforms duty into service.",
    "Honest work strengthens democratic institutions.",
    "Public welfare must always come first.",
    "Strong ethics lead to strong administration.",
    "Every decision should reflect public good.",
    "Discipline is the backbone of governance.",
    "Efficient service builds a progressive nation.",
    "Integrity in action inspires confidence.",
    "Accountability ensures administrative excellence.",
    "Commitment to service defines a true officer.",
    "Nation-building begins with responsible governance.",
    "Serve lawfully, act ethically, work diligently."
];
